### ISSUE TITLE
plugin failure: obsidian-universal-renderer Error: Cannot find module 'punycode/' 

### ISSUE THREAD

**Issue by chenhuawei** [dgudim/obsidian-universal-renderer#1]
Plugin failure: obsidian-universal-renderer Error: Cannot find module 'punycode/'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (node:internal/modules/cjs/loader:1054:15)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3879)
    at Module._load (node:internal/modules/cjs/loader:900:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Kt (app.js:1:262413)
    at o (app.js:1:1962247)
    at node_modules/tough-cookie/lib/cookie.js (VM242 plugin:obsidian-universal-renderer:10455:20)

**Comment by dgudim** [comment]
Yeah, I should add this to the readme, this is a known issue. Just open the compiled main.js and replace all 'punycode/' with 'punycode'. I don't know how to properly fix it because I am not that familiar with esbuild.

**Comment by dgudim** [comment]
Should be fixed in https://github.com/dgudim/obsidian-universal-renderer/commit/ba475785f9d6e08829882b6ab62f9f647a4e0377
